### ISSUE TITLE
Warn or error if insufficient initial heating

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/ebtelPlusPlus#32]
A finite amount of heat is required at t=0 in order to calculate the equilibrium temperature and density for the initial conditions. There should be warning or an exception thrown if the heat input at t=0 is 0 (or below some threshold).

Currently, if you specify zero background heating and have setup a time-dependent heating profile which is zero at t=0, you get NaN for the equilibrium temperature and density. See #31

**Comment by jwreep** [comment]
It looks like this breaks specifically when the equilibrium temperature approaches $10^{4}$ K.  

It looks roughly consistent with the RTV scaling laws, as well.  So, for example, for a 40 Mm loop, I'm seeing a breakdown below $10^{-9}$ erg $s^{-1}$ $cm^{-3}$.  

Combining the scalings to relate temperature to heating, $H = 3 (\frac{T}{1.4})^{7/2} L^{-2}$ for H in $10^{-3}$ erg/s/cm^3, T in MK, L in $10^1$ Mm, I find a heating rate of ~6 x $10^{-9}$ to give an equilibrium of 0.01 MK.  

Since this is actually somewhat higher than where the error arises, I would suggest this could be the threshold to throw an exception or warning.
