### ISSUE TITLE
Catch NaNs in static solver

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/ebtelPlusPlus#33]
There is a fix to the adaptive solver to catch NaNs, but not in the static solver. If a NaN is found anywhere in the solution, an exception should be raised rather than just allowing it to silently fail. See #31 for an example.

**Comment by jwreep** [comment]
Since this calculation is sent off to boost,
https://github.com/rice-solar-physics/ebtelPlusPlus/blob/824f76d3da29999096807c0136b8d9ef5c7f0329/source/main.cpp#L108

Would this have to catch the NaNs post facto?  That's a straightforward fix, I think, but if we want to catch at the exact time step it happens, this function would have to be broken apart.

**Comment by wtbarnes** [comment]
You could do it in post. The other method is to use `obs->Observer`. This function gets called at every single timestep of the integrator. `Observe` could call `CheckNan` inside of it and throw an exception if it finds a NaN.

The only thing we'd need to think about is the behavior of `Observe` in the adaptive integrator. Currently, inside of the `while` loop that controls the adaptive integration, the solution is checked for NaNs at each time step and the timestep is refined to avoid NaNs. If `Observe` was checking for NaNs and throwing an error, we'd need to either catch the error or just give up on refining the timestep to deal with NaNs and just be ok with throwing an exception if a NaN occurs at all. 

The latter would probably be easier and would simplify the code quite a bit. It would also be more explicit about failing loudly. I don't think NaNs happen in the adaptive solver anyway.
