### ISSUE TITLE
Add instructions for installing with conda

### ISSUE THREAD

**Issue by wtbarnes** [rice-solar-physics/ebtelPlusPlus#41]
Boost is probably most easily installed with conda. Should include instructions for how to build against these libraries. 

Recently raised by @adamrkob,

> Hi Will,
>
> Sorry to bother again! But I am now working on new machines, and attempting to get it working has put me in the same position as before. A few things have changed for this round, though. Notable is that I am using conda for all installations, and am running python 3.6.
>
> I assume the problem is that I now need to point scans to the relevant directories for where conda puts things.
>
>```
> $ scons --includepath=/usr/local/include,/usr/include/malloc --libpath=/usr/local/lib
>```
>(or similar) worked before, but I am trying to determine what the correct paths are for the conda installed version. If you know these off the top of your head, feel free to let me know. Otherwise, I am using this in hopes of providing a record of the solution for the next time it comes up.
>
>Thanks,
>
>Adam

**Comment by wtbarnes** [comment]
Hi Adam,

This is actually something I've been meaning to document better for a while. I've built ebtel++ against Boost libraries installed with conda, but everytime I forget what the correct paths are and for some reason I haven't bothered to write them down!

You're correct in using the includepath and libpath flags. However, everything you install with conda is going to be under the root of your Anaconda directory. For me, that is `$HOME/anaconda`. If you've installed boost into the root (or default) environment, all of your libs will be in `$HOME/anaconda/lib` and your header files in `$HOME/anaconda/include`.

If I remember correctly, I also had to explicitly state the path to the Boost library for some reason. I think I also had difficulties linking against the dynamic library and need to use the static one.

Hope this is somewhat helpful. I may not get around to looking at this for a couple of weeks. However, if you find something that works, feel free to make a PR to the documentation!

**Comment by adamrkob** [comment]
Sounds good Will,

OK, so here is where it is currently at. I went through with installing all the relevant packages (python, numpy, matplotlib, seaborn, scons and boost via conda), and using the Xcode/came-with-macos gcc, and verifying that the command line tools were installed. When attempting to run scons (note: MacOS with python 3.6.6 via anaconda3), I got the error listed in #20 that malloc.h could not be found:

> g++ -o Radiation_Model/source/OpticallyThick/OpticallyThickIon.o -c -std=c++11 -O3 -I/opt/local/include Radiation_Model/source/OpticallyThick/OpticallyThickIon.cpp
Radiation_Model/source/OpticallyThick/OpticallyThickIon.cpp:15:20: fatal error: malloc.h: No such file or directory
> #include <malloc.h>'

This was changed slightly, but not fully corrected by using:

`scons --includepath=$HOME/anaconda3/include --libpath=$HOME/anaconda3/lib`

SO, I tested commenting out the calls to malloc.h from :
'Radiation_Model/source/OpticallyThick/OpticallyThickIon.cpp
Radiation_Model/source/element.cpp
rsp_toolkit/source/fitpoly.cpp'

(using the call listed above). This allowed me to get further through the scons process, but it then broke on:

`g++ -o bin/ebtel++.run Radiation_Model/source/radiation.o Radiation_Model/source/ionfrac.o Radiation_Model/source/element.o Radiation_Model/source/OpticallyThick/OpticallyThickIon.o rsp_toolkit/source/fitpoly.o rsp_toolkit/source/xmlreader.o rsp_toolkit/source/file.o rsp_toolkit/tinyxml2/tinyxml2.o source/loop.o source/dem.o source/observer.o source/heater.o source/main.o -L/Users/akobelsk/anaconda3/lib -lboost_program_options-mt`
`ld: library not found for -lboost_program_options-mt
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

Changing line 35 of SConstruct by dropping the `-mt` flag so that it reads (in the base ebtelPlusPlus directory): 
`    env.Append(LIBS=['boost_program_options'])`
remedied this issue, and let scons seemingly run to completion. Unfortunately, it didn't give a proper output that ebtel++ could run:

`$ bin/ebtel++.run `
`dyld: Library not loaded: @rpath/libboost_program_options.dylib`
  `Referenced from: /Users/akobelsk/ebtelPlusPlus/bin/ebtel++.run`
  `Reason: image not found`
`Abort trap: 6`

I have just installed the conda gcc compiler, lets see if it fixes things.

**Comment by wtbarnes** [comment]
Note from #30 
> The boost libraries are now available on conda. The versions on conda-forge seem to work best, though for whatever reason you need to link against the static version of program options.
>This should be added to the install instructions and should make it much easier for people to get started.

**Comment by wtbarnes** [comment]
Leaving a note here so that I remember later. For an anaconda install located in `/home/wbarnes/anaconda3` and with `boost` installed in an environment called `ebtelplusplus` on Ubuntu 18.0.4, the following works. Note that for some reason I need to link explicitly against the static version.

```shell
scons --includepath=/home/wbarnes/anaconda3/envs/ebtelplusplus/include --libs=/home/wbarnes/anaconda3/envs/ebtelplusplus/lib/libboost_program_options.a
```
