### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by biswajitmb** [rice-solar-physics/ebtelPlusPlus#74]
Hi,

I am trying to install ebtelPlusPlus, but getting an error while running scons as,
    scons --includepath=/Users/xyz/boost_1_81_0/install_bm/include --libpath=/Users/xyz/boost_1_81_0/install_bm/lib

Getting the following error:

    scons: Reading SConscript files ...
    Using Mac OS X compile options.
    scons: done reading SConscript files.
    scons: Building targets ...
    g++ -o bin/ebtel++.run source/loop.o source/dem.o source/observer.o source/heater.o source/main.o source/util/tinyxml2.o source/util/xmlreader.o -L/Users/xyz/boost_1_81_0/install_bm/lib -lboost_program_options-mt
    ld: library not found for -lboost_program_options-mt
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    scons: *** [bin/ebtel++.run] Error 1

Do you have any idea why I am getting this error?

Thanks!

**Comment by wtbarnes** [comment]
Thanks for the bug report @biswajitmb. Off the top of my head, I'm not sure what the issue might be. How have you installed the boost libraries?

**Comment by biswajitmb** [comment]
I have downloaded boost libraries from https://www.boost.org/users/download/#live
Then follow the procedure.

    cd boost_1_81_0
    ./bootstrap.sh --prefix=.../install_bm --with-python-version=3.10 --with-python-root=...
    ./b2 install --prefix=.../install_bm --with=all
Then exported the installed path in the environment.

Thanks

**Comment by wtbarnes** [comment]
Hmm that should work, assuming the boost installation was successful.

If you do an `ls -L/Users/xyz/boost_1_81_0/install_bm/lib`, is there a built library in that directory called `libboost_program_options-mt.a` or `libboost_program_options-mt.dylib`? The error implies that it is not able to find the library it is trying to link to.

**Comment by wtbarnes** [comment]
The other option with macOS is to install boost with homebrew: https://formulae.brew.sh/formula/boost and then use the following if homebrew does not install libraries to a place that is already in your libpath by default (e.g. `$HOME/homebrew/include` and `$HOME/homebrew/lib` for me):

```
scons --includepath=$HOME/homebrew/include --libpath=$HOME/homebrew/lib
```

**Comment by wtbarnes** [comment]
As a third option, you can install Boost through `conda`. If you go that route, this issue may be useful: https://github.com/rice-solar-physics/ebtelPlusPlus/issues/41#issuecomment-575252938

**Comment by biswajitmb** [comment]
Thanks Will,

In my boost installation library I found, 'libboost_program_options.dylib' instead of 'libboost_program_options-mt.dylib'.

Thus in a next step, I changed 'env.Append(LIBS=['boost_program_options-mt'])' to 'env.Append(LIBS ['boost_program_options'])' in SConstruct script. 

Now scons is running without any error. But I am getting an error while running ebtel from python, as below:

```
        EbtelPlusPlusError: dyld[59583]: Library not loaded: @rpath/libboost_program_options.dylib
        Referenced from: <929DDE2D-AA5D-3BF6-AB4E-156375270ED7> /Users/xyz/ebtelPlusPlus/bin/ebtel++.run
        Reason: tried: '/System/Volumes/Preboot/Cryptexes/OS@rpath/libboost_program_options.dylib' (no such file), '/usr/local/lib/libboost_program_options.dylib' (no such file), '/usr/lib/libboost_program_options.dylib' (no such file, not in dyld cache)
```

It seems that while running ebtel, library path is not considered properly. Though I have exported it in the environment. Do you have any idea about it.

I also have tried by installing boost from Conda, but facing same issue.

Thanks,
Biswajit

**Comment by wtbarnes** [comment]
Apologies that this has been a bit prolonged @biswajitmb. I am able to reproduce your issue when linking against boost as installed with conda. Below, I've included solution that (hopefully!) will work for you using the fix I just pushed in #75. To grab this fix to the `SConstruct` file, please pull down the latest changes using `git`. I've also added an explanation of what the issue was (as I understand it) mainly for my own benefit in case this problem arises in the future!

## Solution

```shell
$ scons --clean  # clean out everything so we're starting fresh
$ scons \
   --includepath=/Users/xyz/boost_1_81_0/install_bm/include \
   --libpath=/Users/xyz/boost_1_81_0/install_bm/lib \
   --linkflags="-rpath /Users/xyz/boost_1_81_0/install_bm/lib" \
   --libs=boost_program_options
```

Note that I've broken this command across multiple lines just for the sake of readability. You don't actually need the `\` and line breaks. With this solution, your previous modification to `env.Append(LIBS=...)` in `SConstruct` is not needed.

## Explanation

There are really two issues happening here. The first is due to different names of the `boost_program_options` library. The `-mt` in `boost_program_options-mt` indicates that the library was built with multi-threading support (see [this page in the boost docs](https://www.boost.org/doc/libs/1_81_0/more/getting_started/unix-variants.html#library-naming)). This is what it is called in my homebrew install of `boost`. This inconsistency is easily worked around by just passing the correct name on your machine with the `--libs` flag as shown in the code snippet above.

The second issue more hairy and has to do, as far as I can tell, with the way the the `boost_program_options` library is built. In the error you posted above, you'll notice that that the error says 

```
Library not loaded: @rpath/libboost_program_options.dylib
```

The `@rpath` variable is used to tell the executable that we're linking the library against, in this case `ebtel++.run`, where to look for the `boost_program_options` library and this does not happen until runtime which is why you do not see this error until you actually run the executable. By default, macOS will look in a set of predefined locations (in your case, `'/System/Volumes/Preboot/Cryptexes/OS@rpath/libboost_program_options.dylib', '/usr/local/lib/libboost_program_options.dylib', '/usr/lib/libboost_program_options.dylib'` as noted in the error above. However, our built library is not in any of these locations. Fortunately, you can tell your OS to look other places when using `@rpath` too. 

There are a few ways to do this, but the easiest I've found is just to use the `-rpath` flag to pass the need path to `g++`. While `scons` does have an `RPATH` option, it annoyingly seems to be ignored on some compilers (inlcuding `clang` I guess) according to the [documentation for the `RPATH` option](https://scons.org/doc/production/HTML/scons-man.html). However, you can get around this by just passing `-rpath` through the `LINKFLAGS` variable as I've done above.

## Helpful Links

The following issues and SO posts were very helpful when sorting out this problem:

- https://stackoverflow.com/questions/27162276/mac-dynamic-library-craziness-may-be-fortran-only
- https://github.com/SCons/scons/issues/2127
- https://wincent.com/wiki/@executable_path,_@load_path_and_@rpath
- https://stackoverflow.com/questions/2339679/what-are-the-differences-between-so-and-dylib-on-macos

**Comment by biswajitmb** [comment]
Thanks Will for the detailed explanation. It is very helpful. It resolved the problem :)

**Comment by wtbarnes** [comment]
Great! Glad that worked.
